title: Sujai Hiremath5
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true
cv_url: "/assets/Sujai_Hiremath_CV.pdf"
linkedin_url: "https://www.linkedin.com/in/sujaihiremath/"
scholar_url: "https://scholar.google.com/citations?user=YOUR_ID"
