title: Sujai Hiremath
theme: jekyll-theme-minimal

links:
  - title: Resume
    url: /resume.pdf
  - title: LinkedIn
    url: https://www.linkedin.com/in/sujaihiremath/
  - title: Email
    url: mailto:sujai[at]example[dot]com
